-- ==========================================
-- 1. PROJECTS TABLE
-- ==========================================
drop table if exists public.projects cascade;

create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone ('utc'::text, now()) not null,
  title text not null,
  category text not null,
  description text,
  image text,
  link text,
  tags text[]
);

alter table public.projects enable row level security;

create policy "Public Read" on public.projects for select to anon, authenticated using (true);
create policy "Admin Insert" on public.projects for insert to authenticated with check (true);
create policy "Admin Update" on public.projects for update to authenticated using (true);
create policy "Admin Delete" on public.projects for delete to authenticated using (true);

-- ==========================================
-- 2. CONTACT MESSAGES TABLE
-- ==========================================
drop table if exists public.contact_messages cascade;

create table public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  phone text,
  subject text,
  message text
);

alter table public.contact_messages enable row level security;

-- ALLOW inserts from both 'anon' (visitors) and 'authenticated' (logged in admins testing the site)
create policy "Allow public inserts" on public.contact_messages for insert to anon, authenticated with check (true);

create policy "Admin Read" on public.contact_messages for select to authenticated using (true);
create policy "Admin Delete" on public.contact_messages for delete to authenticated using (true);

-- ==========================================
-- 3. JOBS TABLE
-- ==========================================
drop table if exists public.jobs cascade;

create table public.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone ('utc'::text, now()) not null,
  title text not null,
  type text not null,
  location text not null,
  description text not null,
  requirements text[] not null,
  salary_range text,
  category text not null
);

alter table public.jobs enable row level security;

create policy "Public Read" on public.jobs for select to anon, authenticated using (true);
create policy "Admin Insert" on public.jobs for insert to authenticated with check (true);
create policy "Admin Update" on public.jobs for update to authenticated using (true);
create policy "Admin Delete" on public.jobs for delete to authenticated using (true);

-- ==========================================
-- 4. TALENT POOL TABLE
-- ==========================================
drop table if exists public.talent_pool cascade;

create table public.talent_pool (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text not null unique
);

alter table public.talent_pool enable row level security;

-- ALLOW inserts from both 'anon' (visitors) and 'authenticated' (logged in admins testing the site)
create policy "Allow public signups" on public.talent_pool for insert to anon, authenticated with check (true);

create policy "Admin view signups" on public.talent_pool for select to authenticated using (true);
create policy "Admin delete signups" on public.talent_pool for delete to authenticated using (true);

-- ==========================================
-- 5. JOB APPLICATIONS TABLE
-- ==========================================
drop table if exists public.job_applications cascade;

create table public.job_applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  job_id bigint references public.jobs(id) on delete set null,
  job_title text not null,
  name text not null,
  email text not null,
  phone text,
  resume_link text not null,
  portfolio_link text
);

alter table public.job_applications enable row level security;

create policy "Allow public applications" on public.job_applications for insert to anon, authenticated with check (true);
create policy "Admin view applications" on public.job_applications for select to authenticated using (true);
create policy "Admin delete applications" on public.job_applications for delete to authenticated using (true);

-- ==========================================
-- 6. BLOGS TABLE
-- ==========================================
drop table if exists public.blogs cascade;

create table public.blogs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  slug text not null unique,
  title text not null,
  excerpt text,
  content text not null,
  image text,
  author text,
  category text,
  tags text[],
  published boolean default false
);

alter table public.blogs enable row level security;

create policy "Public Read Published" on public.blogs for select to anon, authenticated using (published = true);
create policy "Admin Read All" on public.blogs for select to authenticated using (true);
create policy "Admin Insert" on public.blogs for insert to authenticated with check (true);
create policy "Admin Update" on public.blogs for update to authenticated using (true);
create policy "Admin Delete" on public.blogs for delete to authenticated using (true);

-- ==========================================
-- 7. INITIAL SEED DATA
-- ==========================================

-- INSERT INITIAL PROJECTS
insert into public.projects (title, category, description, image, tags, link)
values
  ('wordpress business website', 'Web', 'wordpress business website', 'https://zhpmgiituymdbhikeggw.supabase.co/storage/v1/object/public/project-images/0.8251377308285658.png', array['Wordpress','business','website'], 'https://www.mobintix.app/contact'),
  ('wordpress business website', 'Web', 'wordpress business website', 'https://zhpmgiituymdbhikeggw.supabase.co/storage/v1/object/public/project-images/0.33654351421522266.png', array['Wordpress','business','website'], 'https://www.mobintix.app/contact'),
  ('wordpress business website', 'Web', 'wordpress business website', 'https://zhpmgiituymdbhikeggw.supabase.co/storage/v1/object/public/project-images/0.12962197015689303.png', array['Wordpress','business','website'], 'https://www.mobintix.app/contact'),
  ('wovenstory for a shopify', 'E-Commerce', 'shopify, e-commerce', 'https://zhpmgiituymdbhikeggw.supabase.co/storage/v1/object/public/project-images/0.11041052779867788.png', array['shopify','e-commerce'], 'https://wovenstory.shop'),
  ('business website', 'Web', 'business website', 'https://zhpmgiituymdbhikeggw.supabase.co/storage/v1/object/public/project-images/0.8737538079136248.png', array['business','website','Next.js','MongoDB'], 'https://www.mobintix.app/contact'),
  ('E-Commerce Website', 'Web', 'Comprehensive analytics platform for retailers.', 'https://zhpmgiituymdbhikeggw.supabase.co/storage/v1/object/public/project-images/0.4080530919819991.png', array['Wordpress','PHP','WooCommerce'], 'https://kgmediastudio.com/'),
  ('FinTech Dashboard', 'Web', 'Financial analytics with real-time data visual.', 'https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=800', array['React','TypeScript','D3.js'], 'https://www.mobintix.app/contact'),
  ('E-Commerce Mobile App', 'Mobile', 'Cross-platform shopping app with seamless checkout experience', 'https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=800', array['React Native','Redux','Stripe'], 'https://www.mobintix.app/contact'),
  ('Healthcare Portal', 'Web', 'Patient management system with appointment scheduling and telemedicine', 'https://images.pexels.com/photos/3825517/pexels-photo-3825517.jpeg?auto=compress&cs=tinysrgb&w=800', array['Vue.js','Node.js','MongoDB'], 'https://www.mobintix.app/contact'),
  ('Brand Identity System', 'Design', 'Complete brand identity and design system for a tech startup', 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=800', array['Figma','UI/UX','Brand Design'], 'https://www.mobintix.app/contact'),
  ('Fitness Tracking App', 'Mobile', 'iOS and Android app for tracking workouts and nutrition', 'https://images.pexels.com/photos/4162487/pexels-photo-4162487.jpeg?auto=compress&cs=tinysrgb&w=800', array['Flutter','Firebase','HealthKit'], 'https://www.mobintix.app/contact'),
  ('Luxury Fashion Store', 'E-Commerce', 'High-end e-commerce platform with AR try-on features', 'https://images.pexels.com/photos/972995/pexels-photo-972995.jpeg?auto=compress&cs=tinysrgb&w=800', array['Next.js','Shopify','AR'], 'https://www.mobintix.app/contact'),
  ('SaaS Analytics Platform', 'Web', 'Business intelligence platform for enterprise clients', 'https://images.pexels.com/photos/590022/pexels-photo-590022.jpeg?auto=compress&cs=tinysrgb&w=800', array['Angular','Python','PostgreSQL'], 'https://www.mobintix.app/contact'),
  ('Smart Home Automation', 'IoT', 'Mobile app for integrated smart home device control.', 'https://images.pexels.com/photos/4255476/pexels-photo-4255476.jpeg?auto=compress&cs=tinysrgb&w=800', array['Flutter','IoT','MQTT'], 'https://www.mobintix.app/contact'),
  ('Travel Booking Platform', 'Web', 'Comprehensive travel booking engine with real-time availability.', 'https://images.pexels.com/photos/1271619/pexels-photo-1271619.jpeg?auto=compress&cs=tinysrgb&w=800', array['React','Node.js','PostgreSQL'], 'https://www.mobintix.app/contact'),
  ('Crypto Exchange Wallet', 'Web3', 'Secure non-custodial wallet for managing crypto assets.', 'https://images.pexels.com/photos/844124/pexels-photo-844124.jpeg?auto=compress&cs=tinysrgb&w=800', array['Solidity','Web3.js','Ethereum'], 'https://www.mobintix.app/contact');
  

-- INSERT INITIAL JOBS
insert into public.jobs (title, category, type, location, description, requirements, salary_range)
values
  ('Business Development Associate – Intern', 'Sales', 'Internship', 'Remote', 'Mobintix Infotech is looking for a motivated Business Development Associate – Intern who is eager to learn client acquisition, lead generation, and sales operations in the IT services industry. This internship offers hands-on experience working with real international clients and exposure to mobile app development, web development, SaaS solutions, and automation projects.', array['Strong communication skills in English', 'Interest in business development, sales, or marketing', 'Comfortable working in a remote or hybrid setup', 'Basic understanding of IT services is a plus', 'Self-motivated and eager to learn', 'Available for a 3–6 month internship'], 'Performance-based stipend'),
  ('Full Stack Developer', 'Engineering', 'Full-time', 'Surat, Gujarat (Hybrid)', 'We are looking for a skilled Full Stack Developer to join our core team. You will be responsible for building and maintaining web applications from scratch.', array['Proficiency in React.js and Node.js', 'Experience with PostgreSQL or MongoDB', 'Strong understanding of RESTful APIs', 'Ability to work in a fast-paced environment'], '₹5L - ₹12L per annum'),
  ('UI/UX Designer', 'Design', 'Full-time', 'Remote', 'We need a creative UI/UX Designer to design beautiful and intuitive interfaces for our global clients.', array['Strong portfolio of design projects', 'Proficiency in Figma or Adobe XD', 'Understanding of user-centered design principles', 'Experience with responsive web design'], '₹4L - ₹8L per annum'),
  ('Digital Marketing Specialist', 'Marketing', 'Full-time', 'Surat, Gujarat', 'Lead our digital marketing efforts and help our clients grow their online presence.', array['Proven experience in SEO/SEM', 'Experience with Google Analytics and Search Console', 'Strong communication and analytical skills', 'Ability to manage multiple social media campaigns'], '₹3L - ₹6L per annum');
  
-- INSERT INITIAL BLOGS
insert into public.blogs (slug, title, excerpt, content, image, author, category, tags, published)
values
  ('welcome-to-mobintix', 'Welcome to Mobintix Blog', 'We are excited to launch our new blog where we share insights on technology, design, and innovation.', 'This is the first blog post content. Welcome to Mobintix! We will be sharing our journey, tips, and industry trends here.', 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800', 'Mobintix Team', 'Company', array['Announcement', 'Tech'], true),
  ('future-of-ai-development', 'The Future of AI in Web Development', 'How Artificial Intelligence is reshaping the way we build and interact with the web.', 'Artificial Intelligence is revolutionizing web development... (Content placeholder)', 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800', 'Tech Lead', 'Technology', array['AI', 'Web Dev', 'Future'], true),
  ('mobile-app-trends-2025', 'Mobile App Trends to Watch in 2025', 'From foldable devices to 5G, here are the key trends that will define mobile apps.', 'Mobile technology is evolving at a breakneck pace... (Content placeholder)', 'https://images.pexels.com/photos/50614/pexels-photo-50614.jpeg?auto=compress&cs=tinysrgb&w=800', 'Mobile Team', 'Mobile', array['Trends', 'Mobile App', '2025'], true),
  ('why-clean-code-matters', 'Why Clean Code Matters for Your Business', 'Discover why investing in clean, maintainable code pays off in the long run.', 'Clean code is not just a developer preference; it is a business asset... (Content placeholder)', 'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=800', 'Senior Developer', 'Engineering', array['Best Practices', 'Code Quality'], true);